version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
      golang: latest
    commands:
      - BRANCH="$(echo $CODEBUILD_WEBHOOK_TRIGGER | cut -d '/' -f 2)"
  pre_build:
    on-failure: ABORT
    commands:      
      - ls /root
      - su - 
      - 'cd $HOME/.goenv && git pull --ff-only && cd -'
      - 'goenv install 1.17.3'
      - 'goenv local 1.17.3'
      - ./devutils/schemavalidator/validate_rules.sh "./gates/*/" "./gates/schema/gate_rules_schema.json"
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - python test_app.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - web.py
    - appspec.yml
    - templates/layout.html
    - templates/test.html
    - scripts/mkdir.sh
    - scripts/start_flask.sh
    - scripts/stop_flask1.sh
    - scripts/stop_flask.py
